# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postssubmit',
            old_name='published_date',
            new_name='insurance_renewed_date',
        ),
        migrations.RenameField(
            model_name='postssubmit',
            old_name='text',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='postssubmit',
            old_name='product_image',
            new_name='vehicle_image',
        ),
        migrations.RenameField(
            model_name='postssubmit',
            old_name='title',
            new_name='vehicle_no',
        ),
    ]
